//
//  CurrencyData.swift
//  CurrencyCalculator
//
//  Created by Ferhan Akkan on 3.01.2020.
//  Copyright © 2020 Ferhan Akkan. All rights reserved.
//
struct CurrencyData: Codable {
    let quotes: Quotes
}

struct Quotes: Codable {
    var USDAED: Double
    var USDAFN: Double
    var USDALL: Double
    var USDAMD: Double
    var USDANG: Double
    var USDAOA: Double
    var USDARS: Double
    var USDAUD: Double
    var USDAWG: Double
    var USDAZN: Double
    var USDBAM: Double
    var USDBBD: Double
    var USDBDT: Double
    var USDBGN: Double
    var USDBHD: Double
    var USDBIF: Double
    var USDBMD: Double
    var USDBND: Double
    var USDBOB: Double
    var USDBRL: Double
    var USDBSD: Double
    var USDBTC: Double
    var USDBTN: Double
    var USDBWP: Double
    var USDBYN: Double
    var USDBYR: Double
    var USDBZD: Double
    var USDCAD: Double
    var USDCDF: Double
    var USDCHF: Double
    var USDCLF: Double
    var USDCLP: Double
    var USDCNY: Double
    var USDCOP: Double
    var USDCRC: Double
    var USDCUC: Double
    var USDCUP: Double
    var USDCVE: Double
    var USDCZK: Double
    var USDDJF: Double
    var USDDKK: Double
    var USDDOP: Double
    var USDDZD: Double
    var USDEGP: Double
    var USDERN: Double
    var USDETB: Double
    var USDEUR: Double
    var USDFJD: Double
    var USDFKP: Double
    var USDGBP: Double
    var USDGEL: Double
    var USDGGP: Double
    var USDGHS: Double
    var USDGIP: Double
    var USDGMD: Double
    var USDGNF: Double
    var USDGTQ: Double
    var USDGYD: Double
    var USDHKD: Double
    var USDHNL: Double
    var USDHRK: Double
    var USDHTG: Double
    var USDHUF: Double
    var USDIDR: Double
    var USDILS: Double
    var USDIMP: Double
    var USDINR: Double
    var USDIQD: Double
    var USDIRR: Double
    var USDISK: Double
    var USDJEP: Double
    var USDJMD: Double
    var USDJOD: Double
    var USDJPY: Double
    var USDKES: Double
    var USDKGS: Double
    var USDKHR: Double
    var USDKMF: Double
    var USDKPW: Double
    var USDKRW: Double
    var USDKYD: Double
    var USDKZT: Double
    var USDLAK: Double
    var USDLBP: Double
    var USDLKR: Double
    var USDLSL: Double
    var USDLTL: Double
    var USDLVL: Double
    var USDLYD: Double
    var USDMAD: Double
    var USDMDL: Double
    var USDMGA: Double
    var USDMKD: Double
    var USDMMK: Double
    var USDMNT: Double
    var USDMOP: Double
    var USDMRO: Double
    var USDMUR: Double
    var USDMVR: Double
    var USDMWK: Double
    var USDMXN: Double
    var USDMYR: Double
    var USDMZN: Double
    var USDNAD: Double
    var USDNGN: Double
    var USDNIO: Double
    var USDNOK: Double
    var USDNPR: Double
    var USDNZD: Double
    var USDOMR: Double
    var USDPAB: Double
    var USDPEN: Double
    var USDPGK: Double
    var USDPHP: Double
    var USDPKR: Double
    var USDPLN: Double
    var USDPYG: Double
    var USDQAR: Double
    var USDRON: Double
    var USDRSD: Double
    var USDRUB: Double
    var USDRWP: Double
    var USDSAR: Double
    var USDSBD: Double
    var USDSCR: Double
    var USDSDG: Double
    var USDSEK: Double
    var USDSHP: Double
    var USDSLL: Double
    var USDSOS: Double
    var USDSRD: Double
    var USDSTD: Double
    var USDSVC: Double
    var USDSYP: Double
    var USDSZL: Double
    var USDTHB: Double
    var USDTJS: Double
    var USDTMT: Double
    var USDTND: Double
    var USDTOP: Double
    var USDTRY: Double
    var USDTTD: Double
    var USDTWD: Double
    var USDTZS: Double
    var USDUAH: Double
    var USDUGX: Double
    var USDUSD: Double
    var USDUYU: Double
    var USDUZS: Double
    var USDVEF: Double
    var USDVND: Double
    var USDVUV: Double
    var USDWST: Double
    var USDXAF: Double
    var USDXAG: Double
    var USDXAU: Double
    var USDXCD: Double
    var USDXDR: Double
    var USDXOF: Double
    var USDXPF: Double
    var USDYER: Double
    var USDZAR: Double
    var USDZMK: Double
    var USDZMW: Double
    var USDZWL: Double
}

